version: "3.8"

services:
  # apicras:
  #   container_name: cras-api
  #   build:
  #     context: .
  #     dockerfile: ./dockerfile    
  #   ports: 
  #     - 3000:3000
  #   networks:
  #     - tag-v3-network
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   restart: unless-stopped
  #   environment:
  #     - dbHost=mysql-api-cras

  mysql:
    image: mysql:5.7
    container_name: mysql-api-cras
    restart: always
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306
    expose:
      - 3306
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 1GB
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: tag
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/var/lib/mysql
      # - .\dump.sql:/docker-entrypoint-initdb.d/dump.sql
      # - ./dump-data.sql:/docker-entrypoint-initdb.d/dump-data.sql
    networks:
      - tag-v3-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - tag-v3-network

networks:
  tag-v3-network:


volumes:
  db-volume:
