-- AlterTable
ALTER TABLE `user_identify` MODIFY `income` INTEGER NULL DEFAULT 0,
    MODIFY `kinship` ENUM('RESPONSAVEL', 'CONJUGE', 'FILHO_A', 'ENTEADO_A', 'NETO_A', 'PAI', 'MAE', 'SOGRO_A', 'IRMAO_A', 'GENRO', 'NORA', 'OUTRO', 'NAO_PARENTE') NULL DEFAULT 'OUTRO';
