-- AlterTable
ALTER TABLE `user_identify` MODIFY `kinship` ENUM('RESPONSAVEL', 'CONJUGE', 'FILHO_A', 'ENTEADO_A', 'NETO_A', 'PAI', 'MAE', 'AVO', 'SOGRO_A', 'IRMAO_A', 'GENRO', 'NORA', 'PRIMO_A', 'OUTRO', 'NAO_PARENTE') NULL DEFAULT 'OUTRO';

-- CreateTable
CREATE TABLE `happychild_on_hc` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `canDelete` BOOLEAN NOT NULL DEFAULT true,
    `user_identify_fk` INTEGER NOT NULL,
    `genre` ENUM('MASCULINO', 'FEMININO', 'OUTRO') NOT NULL,
    `color_race` ENUM('BRANCA', 'PRETA', 'PARDA', 'AMARELA', 'INDIGENA', 'NAO_DECLARADO') NOT NULL,
    `cns_number` INTEGER NOT NULL,
    `visiting_time` VARCHAR(191) NOT NULL,
    `visiting_day` ENUM('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO') NOT NULL,
    `has_rcn` BOOLEAN NOT NULL,
    `has_parents_on_rcn` BOOLEAN NOT NULL,
    `primary_caregiver` ENUM('RESPONSAVEL', 'CONJUGE', 'FILHO_A', 'ENTEADO_A', 'NETO_A', 'PAI', 'MAE', 'AVO', 'SOGRO_A', 'IRMAO_A', 'GENRO', 'NORA', 'PRIMO_A', 'OUTRO', 'NAO_PARENTE') NOT NULL,
    `primary_caregiver_education_level` ENUM('ANALFABETO', 'ANALFABETO_FUNCIONAL', 'ENSINO_FUNDAMENTAL_INCOMPLETO', 'ENSINO_FUNDAMENTAL_COMPLETO', 'ENSINO_MEDIO_INCOMPLETO', 'ENSINO_MEDIO_COMPLETO', 'ENSINO_SUPERIOR_INCOMPLETO', 'ENSINO_SUPERIOR_COMPLETO', 'NAO_INFORMADO') NOT NULL,
    `currently_studying` BOOLEAN NOT NULL,
    `where_studying` VARCHAR(191) NOT NULL DEFAULT '',
    `currently_working` BOOLEAN NOT NULL,
    `where_working` VARCHAR(191) NOT NULL DEFAULT '',
    `profession` VARCHAR(191) NOT NULL DEFAULT '',
    `working_hours` INTEGER NOT NULL DEFAULT 0,
    `cardeneta_saude_or_other` ENUM('CARDENETA', 'OUTRO', 'CARTAO_DE_VACINAS', 'NAO') NOT NULL,
    `lil_feet_test` ENUM('SIM', 'NAO', 'AGENDADO') NOT NULL DEFAULT 'NAO',
    `lil_eye_test` ENUM('SIM', 'NAO', 'AGENDADO') NOT NULL DEFAULT 'NAO',
    `lil_heart_test` BOOLEAN NOT NULL,
    `lil_ear_test` ENUM('SIM', 'NAO', 'AGENDADO') NOT NULL DEFAULT 'NAO',
    `has_childs_weight` BOOLEAN NOT NULL,
    `updated_vaccine_schedule` BOOLEAN NOT NULL,
    `is_breastfed` ENUM('SIM_EXCLUSIVAMENTE', 'SIM_PREDOMINANTEMENTE', 'SIM_COMPLEMENTARMENTE', 'NAO') NOT NULL,
    `breastfeeding_age` ENUM('UM_MES', 'DOIS_MESES', 'TRES_MESES', 'QUATRO_MESES', 'CINCO_MESES', 'SEIS_MESES', 'MAIS_SEIS_MESES', 'NUNCA_MAMOU') NOT NULL,
    `health_problem` BOOLEAN NOT NULL DEFAULT false,
    `sickleCellDisease` BOOLEAN NOT NULL DEFAULT false,
    `anemia` BOOLEAN NOT NULL DEFAULT false,
    `asthma` BOOLEAN NOT NULL DEFAULT false,
    `diabetes` BOOLEAN NOT NULL DEFAULT false,
    `hypertension` BOOLEAN NOT NULL DEFAULT false,
    `gastroesophagealRefluxDisease` BOOLEAN NOT NULL DEFAULT false,
    `cardiovascularDiseases` BOOLEAN NOT NULL DEFAULT false,
    `hivExposure` BOOLEAN NOT NULL DEFAULT false,
    `otherSTIExposure` BOOLEAN NOT NULL DEFAULT false,
    `congenitalSyphilis` BOOLEAN NOT NULL DEFAULT false,
    `epilepsySeizures` BOOLEAN NOT NULL DEFAULT false,
    `cleftLipPalate` BOOLEAN NOT NULL DEFAULT false,
    `mouthBreather` BOOLEAN NOT NULL DEFAULT false,
    `hyperactivityAttentionDeficit` BOOLEAN NOT NULL DEFAULT false,
    `lactoseIntolerance` BOOLEAN NOT NULL DEFAULT false,
    `proteinIntolerance` BOOLEAN NOT NULL DEFAULT false,
    `glutenIntolerance` BOOLEAN NOT NULL DEFAULT false,
    `health_otherCondition` VARCHAR(191) NOT NULL DEFAULT '',
    `medical_monitoring` BOOLEAN NOT NULL DEFAULT false,
    `cardiology` BOOLEAN NOT NULL DEFAULT false,
    `endocrinology` BOOLEAN NOT NULL DEFAULT false,
    `physiotherapy` BOOLEAN NOT NULL DEFAULT false,
    `speechTherapy` BOOLEAN NOT NULL DEFAULT false,
    `pediatrics` BOOLEAN NOT NULL DEFAULT false,
    `pulmonology` BOOLEAN NOT NULL DEFAULT false,
    `neuropediatrics` BOOLEAN NOT NULL DEFAULT false,
    `ophthalmology` BOOLEAN NOT NULL DEFAULT false,
    `psychology` BOOLEAN NOT NULL DEFAULT false,
    `gastroenterology` BOOLEAN NOT NULL DEFAULT false,
    `infectiology` BOOLEAN NOT NULL DEFAULT false,
    `dentistry` BOOLEAN NOT NULL DEFAULT false,
    `psychopedagogy` BOOLEAN NOT NULL DEFAULT false,
    `occupationalTherapy` BOOLEAN NOT NULL DEFAULT false,
    `musicTherapy` BOOLEAN NOT NULL DEFAULT false,
    `equotherapy` BOOLEAN NOT NULL DEFAULT false,
    `proteinIntoleranceSpecialist` BOOLEAN NOT NULL DEFAULT false,
    `glutenIntoleranceSpecialist` BOOLEAN NOT NULL DEFAULT false,
    `otherDoctor` VARCHAR(191) NOT NULL DEFAULT '',
    `notBeingFollowed` BOOLEAN NOT NULL DEFAULT false,
    `medical_service` ENUM('AMBULATORIO_DE_ESPECIALIDADES_HOSPITAL_PUBLICO', 'CENTRO_DE_ESPECIALIDADES_SUS', 'UNIDADE_BASICA_DE_SAUDE_UBS', 'NUCLEO_DE_APOIO_A_SAUDE_DA_FAMILIA_NASF', 'SERVICO_DE_ATENDIMENTO_ESPECIALIZADO_EM_DST_AIDS', 'CENTRO_DE_ATENCAO_PSICOSSOCIAL_CAPS', 'APAE', 'FUNDACAO_ASSOCIACAO_INSTITUTO', 'CLINICA_OU_CONSULTORIO_PARTICULAR', 'OUTRO') NOT NULL,
    `has_disability` BOOLEAN NOT NULL DEFAULT false,
    `disability_type` ENUM('FISICA', 'INTELECTUAL', 'VISUAL', 'AUDITIVA', 'MULTIDEFICIENCIA', 'NAO_DECLARADA') NOT NULL,
    `birth_type` ENUM('PARTO_NORMAL', 'PARTO_CESAREA', 'PARTO_FORCEPS', 'NAO_DECLARADO') NOT NULL,
    `gestational_age_weeks` INTEGER NOT NULL DEFAULT 0,
    `gestational_age_days` INTEGER NOT NULL DEFAULT 0,
    `premature_birth` BOOLEAN NOT NULL DEFAULT false,
    `pregnancy_observations` VARCHAR(191) NOT NULL DEFAULT '',
    `is_in_childhood_education` BOOLEAN NOT NULL,
    `entry_year` INTEGER NOT NULL DEFAULT 0,
    `diff_with_children` BOOLEAN NOT NULL,
    `diff_with_children_description` VARCHAR(191) NOT NULL DEFAULT '',
    `plays_more_with` ENUM('ADULTOS', 'CRIANCAS', 'SOZINHA') NOT NULL,
    `where_plays` VARCHAR(191) NOT NULL DEFAULT '',
    `plays_with_eletronics` BOOLEAN NOT NULL,
    `eletronics_time` ENUM('NAO', 'ATE_2_HORAS', 'ATE_4_HORAS', 'MAIS_QUE_4_HORAS') NOT NULL,
    `watches_tv` BOOLEAN NOT NULL,
    `tv_time` ENUM('NAO', 'ATE_2_HORAS', 'ATE_4_HORAS', 'MAIS_QUE_4_HORAS') NOT NULL,
    `sleep_time` ENUM('ATE_10_HORAS_DIARIAS', 'ENTRE_10_E_11_HORAS_DIARIAS', 'ENTRE_12_E_15_HORAS_DIARIAS', 'ENTRE_15_E_16_HORAS_DIARIAS') NOT NULL,
    `who_lives_with` ENUM('RESPONSAVEL', 'CONJUGE', 'FILHO_A', 'ENTEADO_A', 'NETO_A', 'PAI', 'MAE', 'AVO', 'SOGRO_A', 'IRMAO_A', 'GENRO', 'NORA', 'PRIMO_A', 'OUTRO', 'NAO_PARENTE') NOT NULL,
    `family_play_time` ENUM('TODOS_OS_DIAS', 'UMA_VEZ_POR_SEMANA', 'NAO') NOT NULL,
    `talk_to_the_child` ENUM('FREQUENTEMENTE', 'RARAMENTE', 'NUNCA') NOT NULL,
    `has_kids_book_at_home` BOOLEAN NOT NULL,
    `show_books` ENUM('FREQUENTEMENTE', 'RARAMENTE', 'NUNCA') NOT NULL,
    `tells_stories` ENUM('FREQUENTEMENTE', 'RARAMENTE', 'NUNCA') NOT NULL,
    `sings` ENUM('FREQUENTEMENTE', 'RARAMENTE', 'NUNCA') NOT NULL,
    `walks_with_child` ENUM('FREQUENTEMENTE', 'RARAMENTE', 'NUNCA') NOT NULL,
    `affection` ENUM('CARINHO', 'BEIJOS', 'ABRACOS', 'PALAVRAS_POSITIVAS', 'NENHUM') NOT NULL,
    `affection_other` VARCHAR(191) NOT NULL DEFAULT '',
    `comments` VARCHAR(191) NOT NULL DEFAULT '',

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pregnant_on_hc` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `canDelete` BOOLEAN NOT NULL DEFAULT true,
    `nis_number` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `cellphone_number` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `birthday` DATETIME(3) NOT NULL,
    `age` INTEGER NOT NULL,
    `filiation_1` VARCHAR(191) NULL DEFAULT 'Não declarado',
    `filiation_2` VARCHAR(191) NULL DEFAULT '',
    `color_race` ENUM('BRANCA', 'PRETA', 'PARDA', 'AMARELA', 'INDIGENA', 'NAO_DECLARADO') NOT NULL,
    `sus_number` INTEGER NOT NULL,
    `visiting_time` VARCHAR(191) NOT NULL,
    `visiting_day` ENUM('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO') NOT NULL,
    `gestation_time` INTEGER NOT NULL,
    `parents_location` ENUM('MESMO_BAIRRO', 'OUTRO_BAIRRO', 'NAO') NOT NULL,
    `can_read_write` BOOLEAN NOT NULL,
    `study_now` BOOLEAN NOT NULL,
    `where_study` VARCHAR(191) NOT NULL DEFAULT '',
    `work_now` BOOLEAN NOT NULL,
    `where_work` VARCHAR(191) NOT NULL DEFAULT '',
    `marital_status` ENUM('SOLTEIRO_A', 'CASADO_A', 'UNIAO_ESTAVEL', 'DIVORCIADO_A', 'VIUVO_A', 'DIVORCIADO', 'SEPARADO', 'NAO_INFORMADA') NOT NULL,
    `lives_with` ENUM('RESPONSAVEL', 'CONJUGE', 'FILHO_A', 'ENTEADO_A', 'NETO_A', 'PAI', 'MAE', 'AVO', 'SOGRO_A', 'IRMAO_A', 'GENRO', 'NORA', 'PRIMO_A', 'OUTRO', 'NAO_PARENTE') NOT NULL,
    `prenatal_init` ENUM('NAO_INICIOU', 'ATE_12_SEMANAS', 'ENTRE_13_24_SEMANAS', 'ENTRE_25_36_SEMANAS') NOT NULL,
    `prenatal_number` INTEGER NOT NULL,
    `prenatal_partner` ENUM('SIM_EVENTUALMENTE', 'SIM_SEMPRE', 'APENAS_QUANDO_SOLICITADO', 'NAO_ACOMPANHA') NOT NULL,
    `gestational_period` ENUM('MENOS_DE_22_SEMANAS', 'DE_22_A_27_SEMANAS', 'DE_28_A_31_SEMANAS', 'DE_32_A_36_SEMANAS') NOT NULL,
    `planned_pregnancy` BOOLEAN NOT NULL,
    `sleep_good` BOOLEAN NOT NULL,
    `physical_exercise` BOOLEAN NOT NULL,
    `medical_service` ENUM('AMBULATORIO_DE_ESPECIALIDADES_HOSPITAL_PUBLICO', 'CENTRO_DE_ESPECIALIDADES_SUS', 'UNIDADE_BASICA_DE_SAUDE_UBS', 'NUCLEO_DE_APOIO_A_SAUDE_DA_FAMILIA_NASF', 'SERVICO_DE_ATENDIMENTO_ESPECIALIZADO_EM_DST_AIDS', 'CENTRO_DE_ATENCAO_PSICOSSOCIAL_CAPS', 'APAE', 'FUNDACAO_ASSOCIACAO_INSTITUTO', 'CLINICA_OU_CONSULTORIO_PARTICULAR', 'OUTRO') NOT NULL,
    `medical_service_other` VARCHAR(191) NOT NULL DEFAULT '',
    `knows_maternity` BOOLEAN NOT NULL,
    `where_maternity` VARCHAR(191) NOT NULL DEFAULT '',
    `birth_type` ENUM('PARTO_NORMAL', 'PARTO_CESAREA', 'PARTO_FORCEPS', 'NAO_DECLARADO') NOT NULL,
    `birth_type_justification` VARCHAR(191) NOT NULL DEFAULT '',
    `pregnants_group` BOOLEAN NOT NULL,
    `pregnants_group_where` VARCHAR(191) NOT NULL DEFAULT '',
    `pregnant_questions` VARCHAR(191) NOT NULL DEFAULT '',
    `family_support` BOOLEAN NOT NULL,
    `support_pospartum` BOOLEAN NOT NULL,
    `support_pospartum_who` VARCHAR(191) NOT NULL DEFAULT '',
    `want_partum_companion` BOOLEAN NOT NULL,
    `want_partum_companion_who` VARCHAR(191) NOT NULL DEFAULT '',
    `knows_rn` BOOLEAN NOT NULL,
    `baby_layette` ENUM('POR_CONTA_PROPRIA', 'BENEFICIO_SOCIAL', 'AINDA_NAO_ESTA_FAZENDO') NOT NULL,
    `continue_pcf` BOOLEAN NOT NULL,
    `expectation_pcf` VARCHAR(191) NOT NULL DEFAULT '',
    `previously_pregnant` ENUM('NENHUMA_VEZ', 'UMA_VEZ', 'DUAS_VEZES', 'TRES_OU_MAIS_VEZES') NOT NULL,
    `livebirths_number` ENUM('NENHUM', 'UM', 'DOIS', 'TRES_OU_MAIS') NOT NULL,
    `stillbirths_number` ENUM('NENHUM', 'UM', 'DOIS', 'TRES_OU_MAIS') NOT NULL,
    `abortion_number` ENUM('NENHUM', 'UM', 'DOIS', 'TRES_OU_MAIS') NOT NULL,
    `partum_date` DATETIME(3) NOT NULL,
    `partum_result` ENUM('VIVO', 'MORTO', 'ABORTO') NOT NULL,
    `partum_premature` BOOLEAN NOT NULL,
    `partum_premature_weeks` INTEGER NOT NULL DEFAULT 0,
    `partum_type` ENUM('PARTO_NORMAL', 'PARTO_CESAREA', 'PARTO_FORCEPS', 'NAO_DECLARADO') NOT NULL,
    `had_partum_companion` BOOLEAN NOT NULL,
    `had_partum_companion_who` VARCHAR(191) NOT NULL DEFAULT '',
    `postpartum_appointment` BOOLEAN NOT NULL,
    `postpartum_appointment_date` DATETIME(3) NOT NULL,
    `family_planning` BOOLEAN NOT NULL,
    `inactivation_reason` ENUM('FINAL_DE_GESTACAO', 'MUDANCA_DE_ENDERECO', 'DESISTENCIA_DO_PCF', 'FALECIMENTO') NOT NULL,
    `observations` VARCHAR(191) NOT NULL DEFAULT '',
    `live_with_conjugate` BOOLEAN NOT NULL,
    `conjugate_is_father` BOOLEAN NOT NULL,
    `conjugate_full_name` VARCHAR(191) NOT NULL,
    `conjugate_birth_date` DATETIME(3) NOT NULL,
    `conjugate_cns_number` VARCHAR(191) NOT NULL,
    `conjugate_nis_number` VARCHAR(191) NOT NULL,
    `conjugate_instruction_level` ENUM('ANALFABETO', 'ANALFABETO_FUNCIONAL', 'ENSINO_FUNDAMENTAL_INCOMPLETO', 'ENSINO_FUNDAMENTAL_COMPLETO', 'ENSINO_MEDIO_INCOMPLETO', 'ENSINO_MEDIO_COMPLETO', 'ENSINO_SUPERIOR_INCOMPLETO', 'ENSINO_SUPERIOR_COMPLETO', 'NAO_INFORMADO') NOT NULL,
    `conjugate_currently_studing` BOOLEAN NOT NULL,
    `conjugate_work_now` BOOLEAN NOT NULL,
    `conjugate_profession` VARCHAR(191) NOT NULL DEFAULT '',
    `conjugate_work_hours` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `family_on_hc` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `canDelete` BOOLEAN NOT NULL DEFAULT true,
    `nis_number` VARCHAR(191) NOT NULL,
    `uf` VARCHAR(191) NOT NULL,
    `city` VARCHAR(191) NOT NULL,
    `neighborhood` VARCHAR(191) NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `cep` VARCHAR(191) NOT NULL,
    `reference` VARCHAR(191) NOT NULL,
    `area` ENUM('URBANA', 'RURAL', 'OUTRO') NOT NULL,
    `house_walls` ENUM('ALVENARIA', 'MADEIRA_TRATADA', 'MADEIRA_APROVEITADA', 'TAIPA', 'PALHA', 'LONA_PLASTICO', 'OUTRO') NOT NULL,
    `rooms_number` INTEGER NOT NULL,
    `safe_space` ENUM('ESPACO_PARA_BRINCAR', 'SEM_ESPACO_PARA_BRINCAR', 'ESPACO_SEGURO_PARA_CRIANCA', 'ESPACO_SEM_SEGURANCA_PARA_CRIANCA') NOT NULL,
    `water_supply` ENUM('REDE_PUBLICA', 'POCO_NASCENTE', 'CISTERNA', 'CARRO_PIPA', 'CACIMBA', 'CHAFARIZ', 'OUTRA') NOT NULL,
    `water_supply_other` VARCHAR(191) NOT NULL DEFAULT '',
    `treated_water` BOOLEAN NOT NULL,
    `has_bathroom` BOOLEAN NOT NULL,
    `has_electricity` BOOLEAN NOT NULL,
    `has_cellphone` BOOLEAN NOT NULL,
    `has_cellphone_internet` BOOLEAN NOT NULL,
    `has_refrigerator` BOOLEAN NOT NULL,
    `has_gas_stove` BOOLEAN NOT NULL,
    `has_tv` BOOLEAN NOT NULL,
    `has_radio` BOOLEAN NOT NULL,
    `has_newspaper` BOOLEAN NOT NULL,
    `has_computer` BOOLEAN NOT NULL,
    `has_computer_internet` BOOLEAN NOT NULL,
    `has_other_eletronics` BOOLEAN NOT NULL,
    `other_eletronics` VARCHAR(191) NOT NULL DEFAULT '',
    `has_car` BOOLEAN NOT NULL,
    `has_motorcycle` BOOLEAN NOT NULL,
    `has_bicycle` BOOLEAN NOT NULL,
    `has_public_transport` BOOLEAN NOT NULL,
    `has_other_transport` BOOLEAN NOT NULL,
    `other_transport` VARCHAR(191) NOT NULL DEFAULT '',
    `social_benefits` BOOLEAN NOT NULL,
    `social_benefits_which` VARCHAR(191) NOT NULL DEFAULT '',
    `residents_number` INTEGER NOT NULL,
    `family_speaks_other_lang` BOOLEAN NOT NULL,
    `family_speaks_other_lang_which` VARCHAR(191) NOT NULL DEFAULT '',
    `family_head` ENUM('RESPONSAVEL', 'CONJUGE', 'FILHO_A', 'ENTEADO_A', 'NETO_A', 'PAI', 'MAE', 'AVO', 'SOGRO_A', 'IRMAO_A', 'GENRO', 'NORA', 'PRIMO_A', 'OUTRO', 'NAO_PARENTE') NOT NULL,
    `family_head_phone_number` VARCHAR(191) NOT NULL,
    `family_head_ocupation` VARCHAR(191) NOT NULL DEFAULT '',
    `family_contribution` BOOLEAN NOT NULL,
    `family_contribution_who` VARCHAR(191) NOT NULL DEFAULT '',
    `residents_0_3` BOOLEAN NOT NULL,
    `residents_4_6` BOOLEAN NOT NULL,
    `residents_7_12` BOOLEAN NOT NULL,
    `residents_13_18` BOOLEAN NOT NULL,
    `residents_19_59` BOOLEAN NOT NULL,
    `residents_60_more` BOOLEAN NOT NULL,
    `residents_0_3_number` INTEGER NOT NULL DEFAULT 0,
    `residents_4_6_number` INTEGER NOT NULL DEFAULT 0,
    `residents_childrens_served` BOOLEAN NOT NULL,
    `people_with_disabilities` BOOLEAN NOT NULL,
    `alcool_abuse` BOOLEAN NOT NULL,
    `drug_abuse` BOOLEAN NOT NULL,
    `unemployed` BOOLEAN NOT NULL,
    `inmate` BOOLEAN NOT NULL,
    `inmate_open_regime` BOOLEAN NOT NULL,
    `inmate_socio_edu_measures` BOOLEAN NOT NULL,
    `mother_with_deceased_child` BOOLEAN NOT NULL,
    `mother_with_stillbirth` BOOLEAN NOT NULL,
    `domestic_animals` BOOLEAN NOT NULL,
    `number_of_cats` INTEGER NOT NULL DEFAULT 0,
    `number_of_dogs` INTEGER NOT NULL DEFAULT 0,
    `number_of_birds` INTEGER NOT NULL DEFAULT 0,
    `other_animals` VARCHAR(191) NOT NULL DEFAULT '',
    `primary_caregiver_of_children` VARCHAR(191) NOT NULL,
    `has_pregnant` BOOLEAN NOT NULL,
    `best_visit_period` ENUM('MANHA', 'TARDE', 'NOITE') NOT NULL,
    `best_visit_day` ENUM('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO') NOT NULL,
    `relatives_in_the_city` ENUM('MESMO_BAIRRO', 'OUTRO_BAIRRO', 'NAO') NOT NULL,
    `family_participation_in_community` BOOLEAN NOT NULL,
    `family_religion` ENUM('NENHUMA', 'ATEU', 'CATOLICO', 'EVANGELICO', 'ESPIRITA', 'UMBANDISTA', 'CANDOMBLECISTA', 'BUDISTA', 'JUDEU', 'ISLAMICO', 'OUTROS') NOT NULL,
    `family_religion_other` VARCHAR(191) NOT NULL DEFAULT '',
    `expectation_pcf` VARCHAR(191) NOT NULL DEFAULT '',
    `family_health_care` ENUM('UBS', 'UPA', 'ESF', 'CENTRO_DE_SAUDE', 'HOSPITAL', 'FARMACIA', 'BENZEDEIRA', 'SAMU', 'OUTRO') NOT NULL,
    `family_esf_attendance` BOOLEAN NOT NULL,
    `family_esf_attendance_which` VARCHAR(191) NOT NULL DEFAULT '',
    `family_health_agent_visit` BOOLEAN NOT NULL,
    `family_health_agent_visit_which` VARCHAR(191) NOT NULL DEFAULT '',
    `services_accompanying_family` ENUM('CAPS', 'SAE', 'CRAS', 'CREAS', 'CENTRO_CONVIVENCIA_CRIANCAS_0_6_ANOS', 'CENTRO_CONVIVENCIA_DEMAIS_CICLOS_VIDA', 'CONSELHO_TUTELAR', 'OUTROS', 'NENHUM_DESES') NOT NULL,
    `initial_reception_method_pcf` ENUM('PARTICULARIZADA_CRAS', 'COLETIVA_GRUPOS_CRAS', 'DOMICILIO_VISITADOR_SUPERVISOR', 'COLETIVA_OFICINAS_PAIF', 'ENCONTRO_REUNIAO_INTERSETORIAL') NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
